### ISSUE TITLE
scan in nougat result nothing

### ISSUE THREAD

**Issue by ekhiw** [RobotPajamas/Blueteeth#27]
im using your library for my project
scanForPeripherals result nothing in nougat

**Comment by sureshjoshi** [comment]
Hi, are there any errors that come out?
What kind of phone/OS is it running?
Did you set up runtime permissions?

**Comment by ekhiw** [comment]
im using nokia 6 OS nougat (android 7.1.2)
this is my code, im using kotlin

`BlueteethManager.with(this).scanForPeripherals(DEVICE_SCAN_MILLISECONDS) { blueteethDevices ->
                // Scan completed, iterate through received devices and log their name/mac address
                for (device in blueteethDevices) {
                    Log.d(TAG, "bluetooth device ${device.name}")
                }
            }`

this result nothing in nougat, but work perfecly in lolipop

and i already ask for permission like this
`
        askPermission(Manifest.permission.BLUETOOTH,0x5)
        askPermission(Manifest.permission.BLUETOOTH_ADMIN,0x6)
        askPermission(Manifest.permission.BLUETOOTH_PRIVILEGED,0x07)`

`    fun askPermission(permission : String, requestCode: Int){
        if( ContextCompat.checkSelfPermission(this,permission)!= PackageManager.PERMISSION_GRANTED){
            ActivityCompat.requestPermissions(this, Array(permission.length){permission},requestCode)
        }else{
            Log.d(TAG,"permission already granted : $permission")
        }
    }`

**Comment by sureshjoshi** [comment]
Please ensure you also ask for Location permissions at runtime, since Marshmallow, those are required as well.

http://www.sureshjoshi.com/mobile/living-dangerously-android-permissions/

**Comment by ekhiw** [comment]
wow.. thats help me alot
very usefull guide
thanks suresh and keep the good work

**Comment by sureshjoshi** [comment]
No prob, please re-open if you have any more issues!
