### ISSUE TITLE
BlueteethUtils.writeData return NOT_CONNECTED after 22 times send data

### ISSUE THREAD

**Issue by ekhiw** [RobotPajamas/Blueteeth#28]
Whenever i use BlueteethUtils 22 times, the bluetooth device became not connected, and not showing in scan.
i must restart the apps for connecting again
i dont know where i wrong,
thanks before

here my code :
`                    BlueteethUtils.writeData(
                            data.toByteArray(),
                            UUID.fromString(HM_characteristic),
                            UUID.fromString(HM_service),
                            mBlueteethDevice!!,
                            { response: BlueteethResponse? ->
                                Log.d(TAG, "response write alt $response")
                                count_BT++
                            })`

> 12-29 22:15:01.785 20906-22494/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:07.190 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:13.880 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:17.640 20906-20915/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:20.305 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:23.160 20906-21291/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:25.570 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:27.925 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:30.120 20906-22494/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:32.815 20906-22494/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:34.975 20906-20915/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:37.040 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:39.150 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:41.480 20906-20915/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:43.685 20906-22494/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:45.835 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:47.985 20906-22494/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:50.185 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:52.270 20906-22494/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:54.390 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:56.505 20906-20915/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:15:58.590 20906-21291/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NO_ERROR
12-29 22:16:00.760 20906-20916/com.eloktrikel_tek.alienloxv3 D/Disini MainActivity: response write alt NOT_CONNECTED

**Comment by sureshjoshi** [comment]
I'm not sure this if this is still a problem, but the entire library is in the process of being re-written, and those BLE utils are going away/gone.
With the non-utils, I can use the Blueteeth connection for as long as I want, regardless of number of read/writes.
