### ISSUE TITLE
No 'BlueteethManager' Found

### ISSUE THREAD

**Issue by EricLBaker** [RobotPajamas/Blueteeth#38]
The cover page you presented with the example of how to connect looks very promising, although, I can not find any 'blueteeth' or 'bluetooth' manager in any of your files which leaves me clueless as to how to proceed.

-Also, where you use the Kotlin files blueteethDevice and blueteeth, are those, supposed to be implemented in the java example you have posted that I am trying to make use of?

**Comment by sureshjoshi** [comment]
Sorry, my documentation is out of date from the last few updates. 

I've re-factored a lot of the code in the last month or two, and the Java project needs to be completely re-done and documentation also.

It's on a bucket list of things to do

**Comment by EricLBaker** [comment]
Damn lol, I will be looking forward to it. You don't happen to know where
any other useful documentation of BLE112 is do you? It seems as though
yours was the best, or at least most complete so far. Thanks for your time
man!

**Comment by sureshjoshi** [comment]
If you really wanted to, you could revert back to 0.2.0 of this repo - the docs are in line with that version at least. 

There are a couple of more features I want to add to this repo before bringing the docs in line.

The only documentation I have on the BLE112, I guess you've already seen. The Silicon Labs/Bluegiga datasheets, my blog (http://www.sureshjoshi.com/?s=bluegiga), and my not-recently-updated repo (https://github.com/sureshjoshi/ble113-firmware-examples)

I haven't used the BLE in about a year, as I've moved onto a few other chipsets for anything non-trivial.

**Comment by EricLBaker** [comment]
Yea I have read through just about all of your stuff and I appreciate the
hard work man. If you don't mind me asking, what things have changed from
0.2.0 to the current version? By that I mean, what features in the code are
different?

I have been trying to use pieces of the code you provided just to scan for
a specified server's advertisements (in this case- a program I have
advertising a UUID"), although, I cant seem to get the results to read out
from the scan, which makes it hard to get a connection established. Thanks
for your time!!

-Eric

**Comment by sureshjoshi** [comment]
I think mostly it was just working on a port to Kotlin, because I've basically stopped all Java development since Kotlin 1.1.0...

Also, it was to start cleaning up the code - which was/is a hot steaming mess. 

The only significant feature I think is that I'm working on pulling in my SerialDispatcher library into the latest version of the code, so that we can do queued operations, instead of callback operations. This also brings things like timeouts into play. 

If you're not seeing scan results, make sure you've enabled coarse or fine location permissions in your app. If you don't have that, then scans won't work.

**Comment by EricLBaker** [comment]
I gotchya - I'm not familiar with Kotlin so I'll have to stick to Java for
now. I do have the locations permissions enabled, but I'm working through
some other little bugs. Anyway, the idea about queues definitely sounds
useful, good luck with that!

-Eric
