### ISSUE TITLE
Devices not found using Android Q

### ISSUE THREAD

**Issue by darrinps** [RobotPajamas/Blueteeth#46]
I pulled the code and ran the blueteeth-sample and debugged into it. See that the DeviceScanViewModel devices = 0 when the stateHandler.notScanning() is hit. Tried it several times and verified that several bluetooth devices were active and within range using another app. 

Note that I updated the compileSdkVersion to 28 and made the target that as well. Also, I converted to use AndroidX as I saw that was an ask. Shouldn't be impacting it though.

**Comment by sureshjoshi** [comment]
Hey @darrinps, thanks for pointing that out.

I haven't installed Q yet, but it looks like there was (yet another) change to Bluetooth permissions in Android Q (https://developer.android.com/preview/privacy/camera-connectivity#fine-location-telephony-wifi-bt).

It seems that `ACCESS_FINE_LOCATION` is now required when targeting 29... But, strangely, when not targeting Q, the apps should continue to work.

Also, the changes are specifically around scanning for Bluetooth devices:

`startDiscovery()`
`startLeScan()`
`LeScanCallback()`

**Comment by sureshjoshi** [comment]
@darrinps Just updated my phone to Android Q - I was able to get it scanning by turning on Location Services. I also made some modifications, not sure if they are related to the fix. I will push those anyways, just in case.

**Comment by darrinps** [comment]
Did you ever push those changes? Both Bluetooth and Location Services are on for me and when I swipe to start scanning, the progress indicator spins for a few seconds and nothing is ever displayed. I am seeing several BLE devices with another app though so I know there are plenty by me.

**Comment by darrinps** [comment]
Note that I did convert your code to use AndroidX. I suppose it could be finding but not displaying. I'll check that out.

**Comment by darrinps** [comment]
Nope. Devices.size = 0 in the startScan method of DeviceScanViewModel after the scanning completes. It's just not finding any.

**Comment by sureshjoshi** [comment]
Hey @darrinps maybe check here? 
https://github.com/RobotPajamas/Blueteeth/tree/feature/46-androidq-support

Need to use FINE_LOCATION, setup permissions, and I guess have location + bluetooth enabled

**Comment by darrinps** [comment]
Thanks for the super fast reply. I am seeing this in your blueteeth-sample app and that doesn't require any permissions. I'll adjust as you mention and try again. Thanks.

**Comment by darrinps** [comment]
BINGO. Works fine now. Thanks

**Comment by sureshjoshi** [comment]
Closed by #53
